import 
{
  AmbientLight,
  BoxGeometry,
  BufferGeometry,
  CapsuleGeometry,
  CircleGeometry,
  Color,
  ConeGeometry,
  Curve,
  CylinderGeometry,
  DirectionalLight,
  DodecahedronGeometry,
  DoubleSide,
  ExtrudeGeometry,
  Float32BufferAttribute,
  Fog,
  Group,
  GridHelper,
  HemisphereLight,
  IcosahedronGeometry,
  LatheGeometry,
  LineSegments,
  LineBasicMaterial,
  Mesh,
  MeshPhongMaterial,
  MeshBasicMaterial,
  OctahedronGeometry,
  Object3D,
  PerspectiveCamera,
  PlaneGeometry,
  RingGeometry,
  Raycaster,
  Scene,
  Shape,
  ShapeGeometry,
  SphereGeometry,
  TetrahedronGeometry,
  TorusGeometry,
  TorusKnotGeometry,
  TubeGeometry,
  Vector2,
  Vector3,
  WireframeGeometry,
  WebGLRenderer
} from "three";

import {OrbitControls} from "./OrbitControls.js";


export let mdl = 
{
  AmbientLight: AmbientLight,
  BoxGeometry: BoxGeometry,
  BufferGeometry: BufferGeometry,
  CapsuleGeometry: CapsuleGeometry,
  CircleGeometry: CircleGeometry,
  Color: Color,
  ConeGeometry: ConeGeometry,
  Curve: Curve,
  CylinderGeometry: CylinderGeometry,
  DirectionalLight: DirectionalLight,
  DodecahedronGeometry: DodecahedronGeometry,
  DoubleSide: DoubleSide,
  ExtrudeGeometry: ExtrudeGeometry,
  Float32BufferAttribute: Float32BufferAttribute,
  Fog: Fog,
  Group: Group,
  GridHelper: GridHelper,
  HemisphereLight: HemisphereLight,
  IcosahedronGeometry: IcosahedronGeometry,
  LatheGeometry: LatheGeometry,
  LineSegments: LineSegments,
  LineBasicMaterial: LineBasicMaterial,
  Mesh: Mesh,
  MeshPhongMaterial: MeshPhongMaterial,
  MeshBasicMaterial: MeshBasicMaterial,
  OctahedronGeometry: OctahedronGeometry,
  OrbitControls: OrbitControls,
  Object3D: Object3D,
  PerspectiveCamera: PerspectiveCamera,
  PlaneGeometry: PlaneGeometry,
  RingGeometry: RingGeometry,
  Raycaster: Raycaster,
  Scene: Scene,
  Shape: Shape,
  ShapeGeometry: ShapeGeometry,
  SphereGeometry: SphereGeometry,
  TetrahedronGeometry: TetrahedronGeometry,
  TorusGeometry: TorusGeometry,
  TorusKnotGeometry: TorusKnotGeometry,
  TubeGeometry: TubeGeometry,
  Vector2: Vector2,
  Vector3: Vector3,
  WireframeGeometry: WireframeGeometry,
  WebGLRenderer: WebGLRenderer,
};
